### ISSUE TITLE
Module should default to 'latest' if no version is specified

### ISSUE THREAD

**Issue by danifr** [bfraser/puppet-grafana#106]
It seems there is no major issue with latest versions https://github.com/bfraser/puppet-grafana/issues/94
I'd be happy to start a PR.

Thoughts?

**Comment by kbon** [comment]
Not only that, but we maintain our own RPM repositories. As such, the version we typically want is indeed "latest", without any RPM iteration specified. Currently we can't configure the Grafana module this way on our EL6 machines, as the mandatory rpm_iteration parameter is "1" by default. We can set version to "latest" and rpm_iteration to blank, but then the module tries to install version "latest-" which doesn't work at all.

In the end, we solved it by modifying install.pp:
```
          if ( $::grafana::rpm_iteration == '' ) {
            $real_rpm_ensure = $::grafana::version
          } else {
            $real_rpm_ensure = "${::grafana::version}-${::grafana::rpm_iteration}"
          }

          package { $::grafana::package_name:
            ensure  => $real_rpm_ensure,
            require => Package['fontconfig']
          }
```
If you create a pull request with a new version default to "latest", I'd suggest also including something like this.

**Comment by dhoppe** [comment]
I think this has been fixed by https://github.com/voxpupuli/puppet-grafana/pull/1.

**Comment by danifr** [comment]
Cool! Thanks! I'll move to the voxpupuli one
