### ISSUE TITLE
Make a release for the current HEAD

### ISSUE THREAD

**Issue by paulgeringer** [bfraser/puppet-grafana#28]
Could you push a tag for this repo to match the release marked as 2.0.2 in the forge?

**Comment by bfraser** [comment]
Hi @paulgeringer my apologies for not remembering to tag the releases. I have just pushed tags for the last release of the 1.x series as well as the [release](https://github.com/bfraser/puppet-grafana/releases/tag/v2.0.2) published as 2.0.2 on the Forge.

The latest commits to the repository, to install the fontconfig dependency on Red Hat / CentOS systems and install Grafana 2.0.2 by default, have not yet been incorporated into a release published to the Forge.
