### ISSUE TITLE
Ability to install from local rpm store 

### ISSUE THREAD

**Issue by tarakpurohit** [bfraser/puppet-grafana#36]
I could not change the package source to our in house Spacewalk. 
I had to do a workaround in *install.pp* by commenting out provider and source.  
```puppet
        'RedHat': {
          package { $::grafana::package_name:
            ensure   => present,
            # provider => 'rpm',
            #source   => $::grafana::package_source
          }
```

It would be helpful if we can use the system default.

**Comment by adamcstephens** [comment]
The git repo has support for installing from a repo instead.

@bfraser Can we get a new forge release with the repo support?

**Comment by bfraser** [comment]
A new version of the module has been [published](https://forge.puppetlabs.com/bfraser/grafana) to the forge, and a [release](https://github.com/bfraser/puppet-grafana/releases/tag/v2.1.0) has been created in GitHub.

Please refer to the [README](https://github.com/bfraser/puppet-grafana/blob/v2.1.0/README.md), specifically use of the ```install_method``` and ```manage_package_repo``` parameters, for details about installing from a local package repository.

@tarakpurohit To support your use case, you would want to set ```install_method``` to 'repo' and ```manage_package_repo``` to false. Please open a new issue if you are having any difficulty.
