### ISSUE TITLE
Support for LDAP configuration

### ISSUE THREAD

**Issue by adamcstephens** [bfraser/puppet-grafana#40]
Grafana 2.1 adds [LDAP support](http://docs.grafana.org/v2.1/installation/ldap/). Unfortunately, this separate config file is written in TOML which looks to be non-trivial to template. I've stubbed out an example that dumps a config hash into TOML, but it requires the toml gem to be installed. In a master setup, this would require the toml gem to be installed in the puppetserver (puppetserver gem install toml). This is only required if you're using the LDAP config hash.

Thoughts on this? I can put the PR together, but wanted to put this out there before getting everything put together.

**Comment by bfraser** [comment]
HI @adamcstephens thanks for your contribution!

This looks good, however I do not have LDAP infrastructure to test with. I have applied the configuration as per the documentation, I can see both the main Grafana configuration and the LDAP configuration being built, however ```grafana-server``` will not start for me.

In checking the log, it looks like Grafana is attempting to use the LDAP configuration as I can see it complaining about the ```bind_dn``` option missing from the config file. This would lead me to believe that the configuration *should* work, but again I can't easily test.

Has this code been tested with a real LDAP implementation, and do we know for certain that it works?

**Comment by adamcstephens** [comment]
We am using this in production with our fork. I've updated the README to reflect the needed bind_dn and bind_password, even though the upstream Grafana docs say its not necessary. (We are using them)

**Comment by bfraser** [comment]
Excellent, thank you.

I do see mention in the [documentation](http://docs.grafana.org/v2.1/installation/ldap/) that Grafana expects a bind DN and password to be supplied.

"By default the configuration expects you to specify a bind DN and bind password. This should be a read only user that can perform ldap searches. When the user DN is found a second bind is performed with the user provided username & password (in the normal Grafana login form)."

I will go ahead and merge. Thanks again!

**Comment by bfraser** [comment]
fulfilled by #43
