### ISSUE TITLE
version 2.1 not found for RPM package

### ISSUE THREAD

**Issue by adamcstephens** [bfraser/puppet-grafana#42]
```
Error: /Stage[main]/Grafana::Install/Package[grafana]/ensure: change from 2.1.0-1 to 2.1.0 failed: Could not update: Failed to update to version 2.1.0, got version 2.1.0-1 instead
```

RPM/yum systems need the iteration in the package version. I can put a PR together, but will need to know what OS you're expecting 2.1.0 to work with?

**Comment by bfraser** [comment]
Hi @adamcstephens thanks for the report!

Yes, a PR would be great since 2.1 should work for RPM/yum systems as well.
