### ISSUE TITLE
version parameter has no effect

### ISSUE THREAD

**Issue by everflux** [bfraser/puppet-grafana#52]
When configuring with '2.1.3' the downloaded version is still '2.1.0' from the default parameters.

**Comment by shanemadden** [comment]
Just ran into this too - it's because `$package_source` is set inside params.pp, which uses the params.pp's `$version`.  That should probably be done inside init.pp or install.pp instead, so the passed value will be respected.

**Comment by domingusj** [comment]
Could it be that the params.pp file has a hyphen instead of an underscore on lines 23 and 28? I was running into problems with the install and after changing the - to a _ I was able to install 2.1.3

**Comment by domingusj** [comment]
I apologize, my comment about the hypen/underscore is incorrect. What actually fixed my issue was deleting /tmp/grafana.deb and then I installed the new version.
