### ISSUE TITLE
Can't override grafana::version with package install

### ISSUE THREAD

**Issue by vide** [bfraser/puppet-grafana#67]
I'm using Hiera and Puppet 3.8 but I guess this doesn't work without Hiera too (don't know if it works with Puppet 4 though). After a little bit of investigation I found that basically is because $version used to create the URL for the package isn't expanded with the data provided by Hiera, so basically it always install the $version defined in grafana::params (2.5.0 right now) even if I specify a different vrsion through Hiera (2.6.0 in my case). I've prepared a path, hope you like it, we can discuss if you prefer another approach to fix this

**Comment by bfraser** [comment]
fixed in acc8075 without resorting to inline templates
