### ISSUE TITLE
Add ability to manage grafana dashboards with Puppet

### ISSUE THREAD

**Issue by petems** [bfraser/puppet-grafana#72]
Would be awesome to be able to setup grafana_dashboards with the module

Looks like @simonpasquier has done some awesome work to do this in the Openstack project: https://github.com/openstack/fuel-plugin-influxdb-grafana/blob/master/deployment_scripts/puppet/modules/lma_monitoring_analytics/lib/puppet/provider/grafana_dashboard/grafana.rb

**Comment by simonpasquier** [comment]
I'll try to send a PR in a week or two. Ping me if nothing happens by that time ;-)

**Comment by jaredledvina** [comment]
Since you asked, @simonpasquier were you able to do this?

**Comment by simonpasquier** [comment]
@jaredledvina I've updated the PR that's adding the grafana_datasource resource since the grafana_dashboard resource depends on it somehow. Please have a look and tell me if it suits your needs.
