### ISSUE TITLE
garethr/docker version requirement too strict

### ISSUE THREAD

**Issue by madAndroid** [bfraser/puppet-grafana#74]
Hi,

We're attempting to use garethr/docker version 5.1, but the version requirements in the `metadata.json` file are too restrictive - would you consider changing this to `>= 3.5.0 <6.0.0` ?

Is there anything preventing this from happening, like incompatible features in version > 5.0 ?

**Comment by mcallaway** [comment]
I have this problem too.

**Comment by mcallaway** [comment]
Applicable PR failing: https://github.com/bfraser/puppet-grafana/pull/65

**Comment by bfraser** [comment]
Docker install method tested using version 5.1.0 of garethr/docker, PR has been merged.
