### ISSUE TITLE
fr: use puppet-archive instead of camptocamp-archive

### ISSUE THREAD

**Issue by ltutar** [bfraser/puppet-grafana#81]
The camptocamp-archive breaks the jenkins puppet run since jenkins needs the puppet-archive. Is it possible to modify this module to use the puppet-archive? Thank you in advance.

**Comment by ltutar** [comment]
this would also take care of https://github.com/bfraser/puppet-grafana/issues/80

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by bfraser** [comment]
Thank you for submitting the PR, this is fixed in #85 and 397f70b
